### PR TITLE
failing test for non-existent attribute sets property to null

### LINKED ISSUE #1: property is being set to undefined on initialization if attribute does not exist
If the attribute does not exist the attribute is read and returns null which overwrites the properties default value.

`new Bind` is reading the `parent` during initialization which we want if the attribute exists but we do not want this if the attribute does not exist.

### PR DESCRIPTION
**Pull request by Mattchewone**
This is a failing test to show that a non-existent attribute causes the property to be called with null.

Closes https://github.com/canjs/can-observable-bindings/issues/1

### CODE REVIEW

File: src/from-attribute.js [hunk 1]
```diff
@@ -105,10 +105,28 @@ canReflect.assignSymbols(ElementAttributeObservable.prototype, {
...
 		});
+
+		// This is to prevent canReflect from reading the parent value and setting the child
+		// when the parent / instance doesn't isn't an attribute
+		const oldStart = bind.start;
+		bind.start = function () {
+			// Don't update the child if the attribute does not exist
+			const origUpdateChild = this._updateChild;
+			// create a noop
+			this._updateChild = function() {
```
Comment (phillipskevin) [inline src/from-attribute.js]: can we just overwrite `_updateChild`?

File: src/from-attribute.js [hunk 2]
```diff
@@ -105,10 +105,28 @@ canReflect.assignSymbols(ElementAttributeObservable.prototype, {
...
 	return function fromAttributeBind (instance) {
-		return new Bind({
+		const bind = new Bind({
 			parent: new ElementAttributeObservable(instance, propertyName, {}, 'attributes'),
 			child: value.to(instance, propertyName),
 			queue: "domUI"
 		});
+
+		// This is to prevent canReflect from reading the parent value and setting the child
+		// when the parent / instance doesn't isn't an attribute
```
Comment (phillipskevin) [inline src/from-attribute.js]: > doesn't isn't

**Review by phillipskevin — CHANGES_REQUESTED** [review]

**Review by phillipskevin — APPROVED** [review]

File: src/from-attribute.js (hunk 1 above)
Comment (Mattchewone) [reply src/from-attribute.js]: Yup for sure

File: src/from-attribute.js (hunk 2 above)
Comment (Mattchewone) [reply src/from-attribute.js]: Sorry wasn't able to get clear english down
